CRUD In registered customers
darkclyan/atm pull request #8
Opened 2023-12-20 23:43 UTC by sdeoliveira-r

Obs.: Tratar erro quando usuário digita um email que não existe no banco de dados ao fazer busca pelo email.

2023-12-22 11:51 UTC, sdeoliveira-r commented
![](https://github.trello.services/images/mini-trello-icon.png) [[DEV] Registered Customers](https://trello.com/c/iDuFyauj/2-dev-registered-customers)

2023-12-22 12:21 UTC, davialcantaraa requested changes

2023-12-22 12:21 UTC, davialcantaraa commented on atm-api/src/controllers/customers.ts
> +    });
When deleting, no returned data is needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-api/src/controllers/customers.ts
>      }
A more useful validation needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-api/src/controllers/customers.ts
> +      message: 'All customers!',
When returning data, no message needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-api/src/controllers/customers.ts
> +        message: 'Customer found!',
When returning data, no message needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-api/src/routes/customers.ts
> +router.delete('/:id', deleteCustomer);
PUT method preferred. Authentication middleware needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-app/src/components/Customers/List.tsx
> +    const [message, setMessage] = useState<string | null>(null);
States with initialization values don't need to a type. 

https://www.typescriptlang.org/pt/docs/handbook/type-inference.html

2023-12-22 12:21 UTC, davialcantaraa commented on atm-app/src/components/Customers/List.tsx
>      const handleCustomers = async () => {
A more detailed function name is preferred. Exemple: `handleGetAllCustomers`, `handleGetCustomers`, etc

2023-12-22 12:21 UTC, davialcantaraa commented on atm-app/src/components/Customers/List.tsx
> +            };
A more useful validation needed

2023-12-22 12:21 UTC, davialcantaraa commented on atm-app/src/components/Customers/List.tsx
> +    const modalContent: React.ReactNode = (
This variable don't need a type. 

https://www.typescriptlang.org/pt/docs/handbook/type-inference.html

2023-12-22 12:21 UTC, davialcantaraa commented on atm-app/src/services/customer/index.ts
You can add a specific type for each function return.

Example:

```ts
// customers.d.ts

export type Customer {
    id: string,
    name: string,
    email: string
}
```

```ts
import { Customer } from "./customers.d.ts"
import { AxiosResponse } from "axios"

export const getCustomer = async (email: string): Promise<AxiosResponse<Customer>> => {
  try {
    const ENDPOINT = `customers/${email}`;
    const response = await axios.get(`${API_URL}${ENDPOINT}`);

    console.log(response.data);
    return response.data;
  } catch (error: any) {
    console.log(error);
    throw error.response.data;
  }
};
```

2023-12-26 18:18 UTC, sdeoliveira-r reviewed
Viewed

2023-12-26 18:21 UTC, sdeoliveira-r reviewed
Fixes

2023-12-26 18:23 UTC, sdeoliveira-r reviewed
Viewed

2024-01-09 12:58 UTC, merged